version: '2'

services:
  postgis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: cartologic
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  cartoview:
    command: bash -c "pwd ; python manage.py makemigrations app_manager ; python manage.py migrate people ; python manage.py migrate && python manage.py loaddata sample_admin.json && python manage.py loaddata json/default_oauth_apps.json && uwsgi --ini uwsgi.ini "
#    command: bash -c "python cartoview_project/manage.py makemigrations app_manager ; python manage.py migrate people ; python manage.py migrate ; python manage.py loaddata sample_admin.json && python manage.py loaddata json/default_oauth_apps.json && python manage.py runserver 0.0.0.0:8000"
    image: cartoview/cartoview:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgis
    env_file:
      - ./django.env
    volumes:
      - "./:/code/"
  geoserver:
    image: geonode/geoserver:2.9.x-oauth2
    volumes:
      - "./geoserver/data:/geoserver_data/data"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - cartoview
      - geoserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
